<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="D:/Java Master Course/Selenium Frameworks/src/test/java/sanitytest/BankManagerLogin.java"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="2.619">
  <properties />
            <testcase name="addCustomer" time="2.619" classname="sanitytest.AddCustomer">
                <failure type="org.testng.internal.reflect.MethodMatcherException"
                  message="
[public void sanitytest.AddCustomer.addCustomer(java.util.Hashtable)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: addCustomer([Parameter{index=0, type=java.util.Hashtable, declaredAnnotations=[]}])
Arguments: [(java.util.Hashtable) {postCode=54002, lastName=Khan, firstName=Qamar, alertText=Customer added successfully},null,null,null]"
              >
<![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void sanitytest.AddCustomer.addCustomer(java.util.Hashtable)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: addCustomer([Parameter{index=0, type=java.util.Hashtable, declaredAnnotations=[]}])
Arguments: [(java.util.Hashtable) {postCode=54002, lastName=Khan, firstName=Qamar, alertText=Customer added successfully},null,null,null]
  org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
  org.testng.internal.Parameters.injectParameters(Parameters.java:886)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
